name: opticbrain_ai
description: A mini AI QueryBot.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_generative_language_api: ^0.2.1
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/OpticBrain.png
    - assets/OpticBrainBlack.png
    - assets/OpticBrainWhite.png
    - assets/github-mark-white.png
  uses-material-design: true
  fonts:
    - family: SFProDisplay
      fonts:
      - asset: assets/SFPRODISPLAYREGULAR.OTF
    - family: ProductSanPro
      fonts:
      - asset: assets/ProSansBold.ttf
